# Generated by Django 2.2.2 on 2019-07-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
