# Generated by Django 2.2.2 on 2019-07-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='referral',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
