# Generated by Django 2.2.2 on 2019-07-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190706_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='referral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='referral',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
